# This file is part of the Symfony Standard project.
#
# Copyright (c) 2015 LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Jon Torrado <jontorrado@gmail.com>

# Learn more about admin services at
# https://sonata-project.org/bundles/admin/master/doc/reference/architecture.html#the-admin-class
services:
#    sonata.admin.post:
#        class: AppBundle\Admin\PostAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
#        arguments:
#            - ~
#            - AppBundle\Entity\Post
#            - ~
#        calls:
#            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
