# This file is part of the Symfony Standard project.
#
# Copyright (c) 2016 LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Jon Torrado <jontorrado@gmail.com>

# Learn more about admin services at
# https://sonata-project.org/bundles/admin/3-x/doc/getting_started/creating_an_admin.html#step-3-register-the-admin-class
services:
#    sonata.admin.post:
#        class: AppBundle\Admin\PostAdmin
#        arguments: [~, AppBundle\Entity\Post, ~]
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: Content, label: Post }
         #Use this if you want translated admin
#        calls:
#            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
