# This file is part of the Symfony Standard project.
#
# Copyright (c) 2016 LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Jon Torrado <jontorrado@gmail.com>

Application\Sonata\UserBundle\Entity\User:
    type: entity
    table: fos_user_user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
